### ISSUE TITLE
[Bug]: No Doco!

### ISSUE THREAD

**Issue by baradhili** [BombenProdukt/blade-icons#4]
### What happened?

No clues as to how to use this in a blade! - not even an example??

### How to reproduce the bug

try and use this in a blade...

### Package Version

1.0.0

### PHP Version

8.2.6

### Laravel Version

10

### Which operating systems does with happen with?

Linux

**Comment by faustbrian** [comment]
https://docs.bombenprodukt.com/packages/blade-icons/1.0/families/heroicons
